// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: greeter.proto

package server

import (
	"context"

	"greeter-server/greeter"
	"greeter-server/internal/logic"
	"greeter-server/internal/svc"
)

type GreeterServer struct {
	svcCtx *svc.ServiceContext
	greeter.UnimplementedGreeterServer
}

func NewGreeterServer(svcCtx *svc.ServiceContext) *GreeterServer {
	return &GreeterServer{
		svcCtx: svcCtx,
	}
}

func (s *GreeterServer) SayHello(ctx context.Context, in *greeter.SayHelloReq) (*greeter.SayHelloResp, error) {
	l := logic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
