// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: greeter.proto

package greeterclient

import (
	"context"

	"greeter-server/greeter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SayHelloReq  = greeter.SayHelloReq
	SayHelloResp = greeter.SayHelloResp

	Greeter interface {
		SayHello(ctx context.Context, in *SayHelloReq, opts ...grpc.CallOption) (*SayHelloResp, error)
	}

	defaultGreeter struct {
		cli zrpc.Client
	}
)

func NewGreeter(cli zrpc.Client) Greeter {
	return &defaultGreeter{
		cli: cli,
	}
}

func (m *defaultGreeter) SayHello(ctx context.Context, in *SayHelloReq, opts ...grpc.CallOption) (*SayHelloResp, error) {
	client := greeter.NewGreeterClient(m.cli.Conn())
	return client.SayHello(ctx, in, opts...)
}
